# Generated by Django 4.2 on 2025-11-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_ubigeo', models.CharField(max_length=6, unique=True)),
                ('region_natural', models.CharField(blank=True, max_length=50, null=True)),
                ('poblacion', models.IntegerField(blank=True, null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('tipo_edad', models.CharField(choices=[('A', 'Años'), ('M', 'Meses'), ('D', 'Días')], max_length=1)),
                ('grupo_etario', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('zona_residencia', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='TipoZoonosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('agente_causante', models.CharField(blank=True, max_length=200, null=True)),
                ('animal_vector', models.CharField(blank=True, max_length=100, null=True)),
                ('periodo_incubacion', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_cie10', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Zoonosis',
                'verbose_name_plural': 'Tipos de Zoonosis',
                'db_table': 'tipo_zoonosis',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_ubigeo', models.CharField(max_length=6, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='core.departamento')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
                'ordering': ['nombre'],
                'unique_together': {('departamento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_ubigeo', models.CharField(max_length=6, unique=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='core.provincia')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'db_table': 'distrito',
                'ordering': ['nombre'],
                'unique_together': {('provincia', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_notificacion', models.DateField()),
                ('semana_epidemiologica', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('codigo_diagnostico', models.CharField(max_length=10)),
                ('tipo_diagnostico', models.CharField(choices=[('P', 'Presuntivo'), ('C', 'Confirmado')], max_length=1)),
                ('estado_caso', models.CharField(choices=[('ACTIVO', 'Activo'), ('RECUPERADO', 'Recuperado'), ('FALLECIDO', 'Fallecido')], default='ACTIVO', max_length=50)),
                ('codigo_diresa', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='core.distrito')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='core.paciente')),
                ('zoonosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='core.tipozoonosis')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'db_table': 'caso',
                'ordering': ['-anio', '-semana_epidemiologica'],
            },
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['anio', 'semana_epidemiologica'], name='caso_anio_05e829_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['anio'], name='caso_anio_ebae51_idx'),
        ),
        migrations.AddIndex(
            model_name='caso',
            index=models.Index(fields=['zoonosis', 'anio'], name='caso_zoonosi_14e10e_idx'),
        ),
    ]
